FROM node:alpine

WORKDIR /var/lib/bitcannon/imports

COPY ./config.json /etc/config.json
COPY ./package.json /var/lib/bitcannon/imports
COPY ./yarn.lock /var/lib/bitcannon/imports

COPY background /var/lib/bitcannon/imports/background

RUN yarn install --production && \
    ln -fs /etc/config.json /var/lib/bitcannon/imports/config.json

CMD ["node", "background/imports.js"]
